basePath: /
definitions:
  models.ErrorResponse:
    properties:
      error:
        example: Username or Password is incorrect
        type: string
    type: object
  models.LoginInput:
    properties:
      password:
        example: "123456"
        type: string
      username:
        example: admin
        type: string
    type: object
  models.LoginResponse:
    properties:
      message:
        example: Login successful
        type: string
      token:
        description: JWT 示例
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        type: string
    type: object
  models.Task:
    properties:
      description:
        type: string
      due_date:
        description: Expiration time
        type: string
      id:
        type: integer
      is_done:
        type: boolean
      reminded:
        description: Has it been reminded
        type: boolean
      title:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Swagger for Gin-based TaskFlow app
  title: TaskFlow API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: User logs in with username and password
      parameters:
      - description: Login Information
        in: body
        name: loginInput
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: User Login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Create Users
      parameters:
      - description: User Information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: User Registration
      tags:
      - Auth
  /tasks:
    get:
      description: Supports pagination and sorting (if needed)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all tasks of the current user
      tags:
      - Tasks
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
